#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""Generate exhaustive self-checking testbenches for a std-cell netlist.

Reads a structural Verilog netlist (e.g. ``aion_cells.v``, generated by ``aion_opt``)
whose modules are built purely from IHP ``sg13g2_*`` combinational standard cells, and
emits one SystemVerilog testbench per module that:

  * sweeps **every** input combination (modules here have <= 9 inputs),
  * compares the DUT outputs against a *gold* model built from the PDK Liberty
    ``function`` attributes -- an oracle independent of the Verilog being tested,
  * XORs the two and fails loudly (``$fatal``) on any mismatch.

The gold model is *structural*: one continuous assign per standard-cell instance, using
the cell's Liberty function with its formal pins substituted by the gold name of the
actual net.  Gold signals never read a DUT signal.

Note on ``sp2bool``: the lctime ``sp2bool`` tool shipped in the container cannot be used
as an oracle for this PDK.  ``lctime/lccommon/net_util.py::get_channel_type()`` classifies
a device as NMOS only when its model name *starts with* ``n``; the IHP models are
``sg13_lv_nmos``/``sg13_lv_pmos``, so every transistor is taken to be a PMOS and even
``sg13g2_inv_1`` comes out as ``Y = True``.  With the model names shimmed it still mis-solves
the deeper series stacks (``nand3_1``, ``nand4_1``, ``nor3_1``).  The Liberty functions were
cross-checked against a transistor-network solve of ``sg13g2_stdcell.cdl`` and agree for
every cell used here.

Every library path is an explicit argument, so the tool is not tied to any one PDK. For the
SG13G2 paths used by this repo, `macros/custom_std_cells/Makefile` fills them in:

    ./run.sh "make -C macros/custom_std_cells generate"

which expands to roughly:

    gen_cell_tb.py macros/custom_std_cells/aion_cells.v \\
        --lib $PDK_ROOT/$PDK/libs.ref/sg13g2_stdcell/lib/sg13g2_stdcell_typ_1p20V_25C.lib \\
        --cell-verilog $PDK_ROOT/$PDK/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v \\
        --cell-verilog $PDK_ROOT/$PDK/libs.ref/sg13g2_stdcell/verilog/sg13g2_udp.v

Both must run inside the EDA container: the PDK lives at /foss/pdks, which the host cannot see.
"""

from __future__ import annotations

import argparse
import itertools
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

SPDX = "// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1"


class GenError(Exception):
    """Fatal, user-facing generator error."""


# --------------------------------------------------------------------------------------
# Verilog netlist parsing
# --------------------------------------------------------------------------------------


@dataclass
class Instance:
    cell: str
    name: str
    conns: dict[str, str]  # formal pin -> actual net


@dataclass
class Module:
    name: str
    inputs: list[str] = field(default_factory=list)
    outputs: list[str] = field(default_factory=list)
    wires: list[str] = field(default_factory=list)
    instances: list[Instance] = field(default_factory=list)


_RE_MODULE = re.compile(r"\bmodule\s+(\w+)\s*\((.*?)\)\s*;", re.S)
_RE_ENDMODULE = re.compile(r"\bendmodule\b")
_RE_DECL = re.compile(r"\b(input|output|wire)\s+(\w+)\s*;")
_RE_INST = re.compile(r"\b(\w+)\s+(\w+)\s*\((.*?)\)\s*;", re.S)
_RE_CONN = re.compile(r"\.(\w+)\s*\(\s*(\w+)\s*\)")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_netlist(path: Path) -> list[Module]:
    """Parse a flat structural Verilog netlist into Module objects.

    Only the subset emitted by aion_opt is supported: scalar ``input``/``output``/``wire``
    declarations and named-port cell instances.  Anything else is rejected loudly.
    """
    src = strip_comments(path.read_text())

    modules: list[Module] = []
    pos = 0
    while True:
        m = _RE_MODULE.search(src, pos)
        if not m:
            break
        end = _RE_ENDMODULE.search(src, m.end())
        if not end:
            raise GenError(f"{path}: module '{m.group(1)}' has no matching 'endmodule'")
        body = src[m.end() : end.start()]
        pos = end.end()

        mod = Module(name=m.group(1))
        port_order = [p.strip() for p in m.group(2).split(",") if p.strip()]

        seen: set[str] = set()
        for kind, sig in _RE_DECL.findall(body):
            if kind == "input":
                if sig not in seen:
                    mod.inputs.append(sig)
            elif kind == "output":
                if sig not in seen:
                    mod.outputs.append(sig)
            elif sig not in mod.inputs and sig not in mod.outputs:
                if sig not in seen:
                    mod.wires.append(sig)
            seen.add(sig)

        declared = set(mod.inputs) | set(mod.outputs)
        missing = [p for p in port_order if p not in declared]
        if missing:
            raise GenError(
                f"{path}: module '{mod.name}' ports {missing} have no input/output declaration"
            )

        # Keep the header port order for the ports; it is what the instantiation uses.
        mod.inputs = [p for p in port_order if p in set(mod.inputs)]
        mod.outputs = [p for p in port_order if p in set(mod.outputs)]

        # Instances: search the body with declarations removed so 'input x;' can't match.
        inst_body = _RE_DECL.sub(" ", body)
        for cell, iname, conn_txt in _RE_INST.findall(inst_body):
            conns = dict(_RE_CONN.findall(conn_txt))
            if not conns:
                raise GenError(
                    f"{path}: module '{mod.name}': instance '{iname}' of '{cell}' uses "
                    "positional or unsupported port connections; only .pin(net) is supported"
                )
            leftover = _RE_CONN.sub(" ", conn_txt).replace(",", " ").strip()
            if leftover:
                raise GenError(
                    f"{path}: module '{mod.name}': instance '{iname}' has unparsable "
                    f"connection text: {leftover!r}"
                )
            mod.instances.append(Instance(cell=cell, name=iname, conns=conns))

        if not mod.instances:
            raise GenError(f"{path}: module '{mod.name}' contains no cell instances")

        modules.append(mod)

    if not modules:
        raise GenError(f"{path}: no modules found")
    return modules


# --------------------------------------------------------------------------------------
# Liberty parsing
# --------------------------------------------------------------------------------------


@dataclass
class LibCell:
    name: str
    directions: dict[str, str] = field(default_factory=dict)
    functions: dict[str, str] = field(default_factory=dict)

    @property
    def inputs(self) -> list[str]:
        return [p for p, d in self.directions.items() if d == "input"]

    @property
    def outputs(self) -> list[str]:
        return [p for p, d in self.directions.items() if d == "output"]


_RE_CELL_OPEN = re.compile(r"^\s*cell\s*\(\s*([\w\\\[\]]+)\s*\)\s*\{")
_RE_PIN_OPEN = re.compile(r"^\s*pin\s*\(\s*([\w\\\[\]]+)\s*\)\s*\{")
_RE_DIRECTION = re.compile(r'^\s*direction\s*:\s*"?(\w+)"?\s*;')
_RE_FUNCTION = re.compile(r'^\s*function\s*:\s*"(.*)"\s*;')


def parse_liberty(path: Path, wanted: set[str]) -> dict[str, LibCell]:
    """Extract pin directions and output functions for the requested cells.

    A simple brace-depth scanner is enough: we only need ``cell(){ pin(){ ... } }`` and
    the leaf attributes ``direction`` and ``function``.
    """
    cells: dict[str, LibCell] = {}
    cur: LibCell | None = None
    cur_depth = 0
    pin: str | None = None
    pin_depth = 0
    depth = 0

    with path.open() as fh:
        for line in fh:
            m = _RE_CELL_OPEN.match(line)
            if m:
                depth += line.count("{") - line.count("}")
                name = m.group(1)
                if name in wanted:
                    cur = LibCell(name=name)
                    cells[name] = cur
                    cur_depth = depth
                    pin = None
                continue

            if cur is not None:
                m = _RE_PIN_OPEN.match(line)
                if m:
                    depth += line.count("{") - line.count("}")
                    pin = m.group(1)
                    pin_depth = depth
                    continue
                if pin is not None:
                    m = _RE_DIRECTION.match(line)
                    if m:
                        cur.directions[pin] = m.group(1)
                    m = _RE_FUNCTION.match(line)
                    if m:
                        cur.functions[pin] = m.group(1)

            depth += line.count("{") - line.count("}")
            if pin is not None and depth < pin_depth:
                pin = None
            if cur is not None and depth < cur_depth:
                cur = None
                pin = None

    missing = sorted(wanted - set(cells))
    if missing:
        raise GenError(
            "the netlist instantiates module(s) that are not standard cells of the given "
            f"library: {', '.join(missing)}\n"
            f"  no 'cell (<name>)' entry for them in {path}\n"
            "  Every instance must be a leaf standard cell, so its function can be taken from "
            "Liberty; sub-modules defined in the netlist itself, cells from another library, or "
            "typo'd cell names cannot be given a gold model. Fix the netlist, or point --lib at "
            "the library that defines these cells."
        )
    return cells


# --------------------------------------------------------------------------------------
# Liberty boolean expression parser
#
# Grammar (loosest binding first):
#   or   := xor  (('+' | '|') xor)*
#   xor  := and  ('^' and)*
#   and  := not  (('*' | '&')? not)*          -- juxtaposition means AND
#   not  := '!' not | atom "'"*
#   atom := '(' or ')' | identifier | '0' | '1'
# --------------------------------------------------------------------------------------


@dataclass
class Node:
    op: str  # 'var' | 'const' | 'not' | 'and' | 'or' | 'xor'
    value: str | int | None = None
    kids: list["Node"] = field(default_factory=list)


_RE_TOKEN = re.compile(r"\s*([A-Za-z_]\w*|\d+|[()+|^*&!'])")


def _tokenize(expr: str) -> list[str]:
    toks: list[str] = []
    pos = 0
    while pos < len(expr):
        m = _RE_TOKEN.match(expr, pos)
        if not m:
            if expr[pos:].strip() == "":
                break
            raise GenError(f"cannot tokenize Liberty expression {expr!r} at offset {pos}")
        toks.append(m.group(1))
        pos = m.end()
    return toks


class _LibExprParser:
    def __init__(self, expr: str):
        self.expr = expr
        self.toks = _tokenize(expr)
        self.i = 0

    def peek(self) -> str | None:
        return self.toks[self.i] if self.i < len(self.toks) else None

    def take(self) -> str:
        tok = self.toks[self.i]
        self.i += 1
        return tok

    def parse(self) -> Node:
        node = self.p_or()
        if self.peek() is not None:
            raise GenError(f"trailing tokens in Liberty expression {self.expr!r}: {self.toks[self.i:]}")
        return node

    def p_or(self) -> Node:
        kids = [self.p_xor()]
        while self.peek() in ("+", "|"):
            self.take()
            kids.append(self.p_xor())
        return kids[0] if len(kids) == 1 else Node("or", kids=kids)

    def p_xor(self) -> Node:
        kids = [self.p_and()]
        while self.peek() == "^":
            self.take()
            kids.append(self.p_and())
        return kids[0] if len(kids) == 1 else Node("xor", kids=kids)

    def p_and(self) -> Node:
        kids = [self.p_not()]
        while True:
            tok = self.peek()
            if tok in ("*", "&"):
                self.take()
                kids.append(self.p_not())
            elif tok is not None and (tok == "(" or tok == "!" or tok[0].isalnum() or tok[0] == "_"):
                # juxtaposition, e.g. "A B" or "A!B"
                kids.append(self.p_not())
            else:
                break
        return kids[0] if len(kids) == 1 else Node("and", kids=kids)

    def p_not(self) -> Node:
        if self.peek() == "!":
            self.take()
            return Node("not", kids=[self.p_not()])
        node = self.p_atom()
        while self.peek() == "'":
            self.take()
            node = Node("not", kids=[node])
        return node

    def p_atom(self) -> Node:
        tok = self.peek()
        if tok is None:
            raise GenError(f"unexpected end of Liberty expression {self.expr!r}")
        if tok == "(":
            self.take()
            node = self.p_or()
            if self.peek() != ")":
                raise GenError(f"missing ')' in Liberty expression {self.expr!r}")
            self.take()
            return node
        self.take()
        if tok.isdigit():
            if tok not in ("0", "1"):
                raise GenError(f"unsupported constant {tok!r} in {self.expr!r}")
            return Node("const", value=int(tok))
        if tok[0].isalpha() or tok[0] == "_":
            return Node("var", value=tok)
        raise GenError(f"unexpected token {tok!r} in Liberty expression {self.expr!r}")


def parse_lib_expr(expr: str) -> Node:
    return _LibExprParser(expr).parse()


def render_sv(node: Node, subst: dict[str, str]) -> str:
    """Render an AST as a fully parenthesised SystemVerilog bit expression."""
    if node.op == "const":
        return "1'b1" if node.value else "1'b0"
    if node.op == "var":
        name = str(node.value)
        if name not in subst:
            raise GenError(f"Liberty function references unconnected pin '{name}'")
        return subst[name]
    if node.op == "not":
        return f"~{render_sv(node.kids[0], subst)}"
    sym = {"and": " & ", "or": " | ", "xor": " ^ "}[node.op]
    return "(" + sym.join(render_sv(k, subst) for k in node.kids) + ")"


def eval_node(node: Node, env: dict[str, int]) -> int:
    if node.op == "const":
        return int(node.value or 0)
    if node.op == "var":
        return env[str(node.value)]
    if node.op == "not":
        return 1 - eval_node(node.kids[0], env)
    vals = [eval_node(k, env) for k in node.kids]
    if node.op == "and":
        return int(all(vals))
    if node.op == "or":
        return int(any(vals))
    if node.op == "xor":
        out = 0
        for v in vals:
            out ^= v
        return out
    raise GenError(f"unknown node op {node.op!r}")


# --------------------------------------------------------------------------------------
# Gold model construction
# --------------------------------------------------------------------------------------


@dataclass
class GoldAssign:
    net: str  # module net driven
    inst: Instance
    out_pin: str
    lib_func: str
    ast: Node
    pin_to_net: dict[str, str]  # formal pin -> module net (inputs of this cell only)


@dataclass
class GoldModel:
    module: Module
    assigns: list[GoldAssign]
    order: list[str]  # topological order of driven nets

    def gold_name(self, net: str) -> str:
        return net if net in self.module.inputs else f"g_{net}"


# Identifiers the testbench template declares itself; a module port using one of these
# would silently shadow it.
TB_RESERVED = {"vec", "dut_o", "gold_o", "diff", "correct", "errors", "u_dut", "v", "NI", "NO"}


def build_gold(mod: Module, lib: dict[str, LibCell]) -> GoldModel:
    inputs = set(mod.inputs)
    driver: dict[str, GoldAssign] = {}

    clashes = sorted(p for p in mod.inputs + mod.outputs if p in TB_RESERVED)
    if clashes:
        raise GenError(
            f"module '{mod.name}': port(s) {clashes} collide with identifiers the testbench "
            "template declares; rename them in the netlist"
        )
    shadowed = sorted(p for p in mod.inputs if p.startswith("g_"))
    if shadowed:
        raise GenError(
            f"module '{mod.name}': input(s) {shadowed} start with 'g_', which is the prefix "
            "used for gold-model signals"
        )

    for inst in mod.instances:
        cell = lib[inst.cell]
        if not cell.functions:
            raise GenError(
                f"module '{mod.name}': cell '{inst.cell}' has no Liberty output function "
                "(sequential or black-box cells are not supported)"
            )
        for pin, net in inst.conns.items():
            if pin not in cell.directions:
                raise GenError(
                    f"module '{mod.name}': instance '{inst.name}' connects pin '{pin}', "
                    f"which is not a pin of '{inst.cell}'"
                )
        for out_pin, func in cell.functions.items():
            if out_pin not in inst.conns:
                raise GenError(
                    f"module '{mod.name}': instance '{inst.name}' leaves output pin "
                    f"'{out_pin}' of '{inst.cell}' unconnected"
                )
            net = inst.conns[out_pin]
            if net in inputs:
                raise GenError(
                    f"module '{mod.name}': instance '{inst.name}' drives primary input '{net}'"
                )
            if net in driver:
                raise GenError(
                    f"module '{mod.name}': net '{net}' is driven by both "
                    f"'{driver[net].inst.name}' and '{inst.name}'"
                )
            ast = parse_lib_expr(func)
            pin_to_net = {p: n for p, n in inst.conns.items() if cell.directions[p] == "input"}
            driver[net] = GoldAssign(
                net=net, inst=inst, out_pin=out_pin, lib_func=func, ast=ast, pin_to_net=pin_to_net
            )

    for out in mod.outputs:
        if out not in driver:
            raise GenError(f"module '{mod.name}': output '{out}' is undriven")

    # Every read net must be a primary input or driven by some instance.
    for ga in driver.values():
        for pin, net in ga.pin_to_net.items():
            if net not in inputs and net not in driver:
                raise GenError(
                    f"module '{mod.name}': instance '{ga.inst.name}' pin '{pin}' reads "
                    f"undriven net '{net}'"
                )

    order = _topo_order(mod, driver, inputs)
    return GoldModel(module=mod, assigns=[driver[n] for n in order], order=order)


def _topo_order(mod: Module, driver: dict[str, GoldAssign], inputs: set[str]) -> list[str]:
    """Depth-first topological sort of the driven nets; raises on a combinational loop."""
    order: list[str] = []
    state: dict[str, int] = {}  # 0 = visiting, 1 = done
    stack: list[str] = []

    def visit(net: str) -> None:
        if state.get(net) == 1:
            return
        if state.get(net) == 0:
            cycle = stack[stack.index(net) :] + [net]
            raise GenError(
                f"module '{mod.name}': combinational loop through nets: {' -> '.join(cycle)}"
            )
        state[net] = 0
        stack.append(net)
        for src in driver[net].pin_to_net.values():
            if src not in inputs:
                visit(src)
        stack.pop()
        state[net] = 1
        order.append(net)

    for net in driver:
        visit(net)
    return order


def gold_sv_expr(gm: GoldModel, ga: GoldAssign) -> str:
    subst = {pin: gm.gold_name(net) for pin, net in ga.pin_to_net.items()}
    return render_sv(ga.ast, subst)


def gold_flat_expr(gm: GoldModel, net: str, cache: dict[str, str]) -> str:
    """Flatten a net's function all the way down to the module's primary inputs."""
    if net in cache:
        return cache[net]
    ga = next(a for a in gm.assigns if a.net == net)
    subst = {}
    for pin, src in ga.pin_to_net.items():
        subst[pin] = src if src in gm.module.inputs else gold_flat_expr(gm, src, cache)
    expr = render_sv(ga.ast, subst)
    cache[net] = expr
    return expr


def gold_truth_table(gm: GoldModel) -> dict[str, list[int]]:
    """Evaluate the gold model over every input vector; also proves it is resolvable."""
    mod = gm.module
    table: dict[str, list[int]] = {o: [] for o in mod.outputs}
    for vals in itertools.product((0, 1), repeat=len(mod.inputs)):
        env = dict(zip(mod.inputs, vals))
        for ga in gm.assigns:  # already topologically ordered
            local = {pin: env[net] for pin, net in ga.pin_to_net.items()}
            env[ga.net] = eval_node(ga.ast, local)
        for o in mod.outputs:
            table[o].append(env[o])
    return table


# --------------------------------------------------------------------------------------
# Emitters
# --------------------------------------------------------------------------------------


def header(script: str, netlist: str, lib: str) -> str:
    return (
        f"{SPDX}\n"
        f"// AUTO-GENERATED by {script} from {netlist} -- do not edit.\n"
        f"// Gold model derived from the Liberty functions in {lib}\n"
    )


def emit_tb(gm: GoldModel, script: str, netlist: str, lib: str) -> str:
    mod = gm.module
    ni = len(mod.inputs)
    no = len(mod.outputs)
    tb = f"tb_{mod.name}"
    w = max(len(gm.gold_name(a.net)) for a in gm.assigns)

    lines: list[str] = []
    add = lines.append
    add(header(script, netlist, lib))
    add("`timescale 1ns/1ps")
    add("`default_nettype none")
    add("")
    add(f"module {tb};")
    add("")
    add(f"  localparam int NI = {ni};")
    add(f"  localparam int NO = {no};")
    add("")
    add("  logic [NI-1:0] vec;")
    for i, sig in enumerate(mod.inputs):
        add(f"  wire {sig} = vec[{i}];")
    add("")
    add("  // ---- DUT ----")
    add("  wire " + ", ".join(mod.outputs) + ";")
    conns = ", ".join(f".{p}({p})" for p in mod.inputs + mod.outputs)
    add(f"  {mod.name} u_dut ({conns});")
    add("")
    add("  // ---- gold: one assign per standard cell, function taken from Liberty ----")
    gold_wires = [gm.gold_name(a.net) for a in gm.assigns]
    add("  wire " + ", ".join(gold_wires) + ";")
    for ga in gm.assigns:
        name = gm.gold_name(ga.net)
        expr = gold_sv_expr(gm, ga)
        add(
            f"  assign {name:<{w}} = {expr};"
            f"  // {ga.inst.name} {ga.inst.cell}: {ga.out_pin} = {ga.lib_func}"
        )
    add("")
    add("  // ---- compare ----")
    cat_dut = "{" + ", ".join(reversed(mod.outputs)) + "}"
    cat_gold = "{" + ", ".join(gm.gold_name(o) for o in reversed(mod.outputs)) + "}"
    add(f"  wire [NO-1:0] dut_o   = {cat_dut};")
    add(f"  wire [NO-1:0] gold_o  = {cat_gold};")
    add("  wire [NO-1:0] diff    = dut_o ^ gold_o;")
    add("  wire          correct = (diff === '0);")
    add("")
    add("  int errors = 0;")
    add("")
    add("  // ---- waveforms: build with VCD=1 (Verilator needs --trace) ----")
    add("`ifdef VCD")
    add("  initial begin")
    add(f'    $dumpfile("{tb}.vcd");')
    add(f"    $dumpvars(0, {tb});")
    add("  end")
    add("`endif")
    add("")
    add("  initial begin")
    add("    for (int unsigned v = 0; v < (1 << NI); v++) begin")
    add("      vec = v[NI-1:0];")
    add("      #1;")
    add("      if (!correct) begin")
    add("        errors++;")
    add(
        f'        $display("[FAIL] {mod.name} vec=%b '
        f'{{{",".join(reversed(mod.outputs))}}}: dut=%b gold=%b diff=%b",'
    )
    add("                 vec, dut_o, gold_o, diff);")
    add("      end")
    add("    end")
    add("    if (errors == 0)")
    add(
        f'      $display("[PASS] {mod.name} : %0d/%0d vectors match", '
        "(1 << NI), (1 << NI));"
    )
    add("    else begin")
    add(
        f'      $display("[FAIL] {mod.name} : %0d/%0d vectors mismatched", '
        "errors, (1 << NI));"
    )
    add('      $fatal(1, "gold/DUT mismatch");')
    add("    end")
    add("    $finish;")
    add("  end")
    add("")
    add("endmodule")
    add("")
    add("`default_nettype wire")
    return "\n".join(lines) + "\n"


def emit_report(
    models: list[GoldModel], tables: dict[str, dict[str, list[int]]], script: str, netlist: str, lib: str
) -> str:
    lines = [
        f"<!-- AUTO-GENERATED by {script} from {netlist} -- do not edit. -->",
        "",
        f"# Gold functions for `{netlist}`",
        "",
        f"Oracle: Liberty `function` attributes from `{lib}`.",
        "",
        "For each module: the per-cell gold equations exactly as emitted into the testbench,",
        "and the same outputs flattened down to the primary inputs for review.",
        "",
    ]
    for gm in models:
        mod = gm.module
        lines.append(f"## `{mod.name}`")
        lines.append("")
        lines.append(
            f"{len(mod.inputs)} inputs (`{', '.join(mod.inputs)}`), "
            f"{len(mod.outputs)} outputs (`{', '.join(mod.outputs)}`), "
            f"{2 ** len(mod.inputs)} exhaustive vectors."
        )
        lines.append("")
        lines.append("| instance | cell | Liberty function | gold equation |")
        lines.append("| --- | --- | --- | --- |")
        for ga in gm.assigns:
            lines.append(
                f"| `{ga.inst.name}` | `{ga.inst.cell}` | `{ga.out_pin} = {ga.lib_func}` | "
                f"`{gm.gold_name(ga.net)} = {gold_sv_expr(gm, ga)}` |"
            )
        lines.append("")
        cache: dict[str, str] = {}
        lines.append("Flattened:")
        lines.append("")
        lines.append("```")
        for o in mod.outputs:
            lines.append(f"{o} = {gold_flat_expr(gm, o, cache)}")
        lines.append("```")
        lines.append("")
        lines.append("Truth table (LSB of the index is the first input):")
        lines.append("")
        lines.append("```")
        for o in mod.outputs:
            bits = "".join(str(b) for b in tables[mod.name][o])
            chunks = [bits[i : i + 64] for i in range(0, len(bits), 64)]
            lines.append(f"{o}: {chunks[0]}")
            pad = " " * (len(o) + 2)
            lines.extend(f"{pad}{c}" for c in chunks[1:])
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


MAKEFILE_TEMPLATE = """\
# AUTO-GENERATED by @SCRIPT@ from @NETLIST@ -- do not edit.
# Exhaustive std-cell testbenches: Verilator and Icarus Verilog.
#
# The paths below were baked in from the generator's command line; override any of
# them on the make command line, e.g. `make all CELL_SRC_IN=/path/to/models.v`.

MAKEFILE_DIR := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))
BUILD        := $(MAKEFILE_DIR)build

NETLIST     ?= $(MAKEFILE_DIR)@NETLISTREL@
CELL_SRC_IN ?= @CELLSRC@

@STRIPBLOCK@
TBS := \\
@TBLIST@

VERILATOR_FLAGS ?= --binary --timing -Wno-TIMESCALEMOD -Wno-DECLFILENAME
IVERILOG_FLAGS  ?= -g2012

# VCD=1 turns on waveform dumping. Each testbench then writes <tb>.vcd next to its
# binary: build/vlt/<tb>/<tb>.vcd for Verilator, build/icarus/<tb>.vcd for Icarus.
ifeq ($(VCD),1)
VERILATOR_FLAGS += --trace +define+VCD
IVERILOG_FLAGS  += -DVCD
endif

.DEFAULT_GOAL := help

help: ## Show this help message
\t@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \\
\t\tawk 'BEGIN {FS = ":.*?## "}; {printf "  \\033[36m%-14s\\033[0m %s\\n", $$1, $$2}'
.PHONY: help

verilator: $(CELL_SRC) ## Run every testbench with Verilator
\t@mkdir -p $(BUILD)/vlt; fail=0; \\
\tfor tb in $(TBS); do \\
\t\tif ! verilator $(VERILATOR_FLAGS) --Mdir $(BUILD)/vlt/$$tb --top-module $$tb -o $$tb \\
\t\t\t\t$(MAKEFILE_DIR)$$tb.sv $(NETLIST) $(CELL_SRC) \\
\t\t\t\t> $(BUILD)/vlt/$$tb.build.log 2>&1; then \\
\t\t\techo "[BUILD-FAIL] $$tb"; cat $(BUILD)/vlt/$$tb.build.log; fail=1; continue; fi; \\
\t\t( cd $(BUILD)/vlt/$$tb && ./$$tb ) > $(BUILD)/vlt/$$tb.run.log 2>&1 || fail=1; \\
\t\tgrep -E '^\\[(PASS|FAIL)\\]' $(BUILD)/vlt/$$tb.run.log \\
\t\t\t|| { echo "[NO-RESULT] $$tb"; cat $(BUILD)/vlt/$$tb.run.log; fail=1; }; \\
\tdone; \\
\tif [ $$fail -ne 0 ]; then echo "verilator: FAILED"; exit 1; fi; \\
\techo "verilator: all $(words $(TBS)) testbenches passed"
.PHONY: verilator

icarus: $(CELL_SRC) ## Run every testbench with Icarus Verilog
\t@mkdir -p $(BUILD)/icarus; fail=0; \\
\tfor tb in $(TBS); do \\
\t\tif ! iverilog $(IVERILOG_FLAGS) -o $(BUILD)/icarus/$$tb.vvp \\
\t\t\t\t$(MAKEFILE_DIR)$$tb.sv $(NETLIST) $(CELL_SRC) \\
\t\t\t\t> $(BUILD)/icarus/$$tb.build.log 2>&1; then \\
\t\t\techo "[BUILD-FAIL] $$tb"; cat $(BUILD)/icarus/$$tb.build.log; fail=1; continue; fi; \\
\t\t( cd $(BUILD)/icarus && vvp $$tb.vvp ) > $(BUILD)/icarus/$$tb.run.log 2>&1 || fail=1; \\
\t\tgrep -E '^\\[(PASS|FAIL)\\]' $(BUILD)/icarus/$$tb.run.log \\
\t\t\t|| { echo "[NO-RESULT] $$tb"; cat $(BUILD)/icarus/$$tb.run.log; fail=1; }; \\
\tdone; \\
\tif [ $$fail -ne 0 ]; then echo "icarus: FAILED"; exit 1; fi; \\
\techo "icarus: all $(words $(TBS)) testbenches passed"
.PHONY: icarus

all: ## Run every testbench with both simulators
\t@$(MAKE) --no-print-directory -C $(MAKEFILE_DIR) verilator
\t@$(MAKE) --no-print-directory -C $(MAKEFILE_DIR) icarus
.PHONY: all

clean: ## Remove simulator build products
\trm -rf $(BUILD)
.PHONY: clean
"""

# Emitted when --strip-specify is on: the cell models are copied into build/ with their
# `specify` blocks removed, since these testbenches check function only.
STRIP_BLOCK = """\
# These testbenches check function only, so the cell models are used with their `specify`
# blocks stripped: no timing, zero-delay gate primitives, and no "sorry: ifnone with an
# edge-sensitive path" complaints from Icarus. The `#1` between stimulus and sampling in
# each testbench is far longer than the (zero) gate delays.
CELL_SRC := $(addprefix $(BUILD)/nospec/,$(notdir $(CELL_SRC_IN)))
vpath %.v $(sort $(dir $(CELL_SRC_IN)))

$(BUILD)/nospec/%.v: %.v
\t@mkdir -p $(dir $@)
\tsed -e '/^[[:space:]]*specify[[:space:]]*$$/,/^[[:space:]]*endspecify[[:space:]]*$$/d' $< > $@

nospec: $(CELL_SRC) ## Build the specify-stripped copies of the cell models
.PHONY: nospec
"""

NO_STRIP_BLOCK = """\
# --no-strip-specify was used: the cell models are compiled as-is, timing and all.
CELL_SRC := $(CELL_SRC_IN)
"""


README_TEMPLATE = """\
<!-- AUTO-GENERATED by @SCRIPT@ from @NETLIST@ -- do not edit. -->

# Exhaustive testbenches for `@NETLIST@`

Every module in `../@NETLIST@` is a small combinational netlist of IHP `sg13g2_*` standard cells,
emitted by `aion_opt`. Because each has few enough inputs, they are verified **exhaustively**: one
SystemVerilog testbench per module sweeps *all* `2^NI` input combinations and XORs the DUT outputs
against a gold model built from an oracle independent of the Verilog under test.

@NTB@ testbenches, @NVEC@ vectors in total, passing under both Verilator and Icarus Verilog.

**Everything in this directory is generated** — see [The generator](#the-generator) below. Edit
`../scripts/@SCRIPTBASE@` and regenerate; do not edit these files by hand.

## Quick start

```bash
# run: both simulators
./run.sh "make -C macros/custom_std_cells/tb all"

# ...or one at a time
./run.sh "make -C macros/custom_std_cells/tb verilator"
./run.sh "make -C macros/custom_std_cells/tb icarus"

# regenerate this directory (only needed after @NETLIST@ changes)
./run.sh "make -C macros/custom_std_cells generate"
```

These must run **inside** the EDA container (via `./run.sh`): the Liberty file the oracle comes
from and the cell simulation models both live under the PDK install, which does not exist on the
host. This directory was generated with:

```
@GENCMD@
```

## Contents

| File | What |
| --- | --- |
| `tb_<module>.sv` | one exhaustive, self-checking testbench per module (@NTB@ of them) |
| `Makefile` | runs them under Verilator and Icarus; see [targets](#the-makefile) |
| `gold_functions.md` | per module: the Liberty function used for each cell instance, the emitted gold equations, the outputs flattened to primary inputs, and the truth tables |
| `README.md` | this file |
| `build/` | simulator build products (`make clean` removes it) |

None of it is tracked by git — `macros/custom_std_cells/.gitignore` ignores this whole directory,
since it is reproducible from `../@NETLIST@` and the PDK.

## What is checked

Each `tb_<module>.sv` drives every input combination and compares the DUT against the gold model
bit by bit:

```systemverilog
wire [NO-1:0] dut_o   = {@CATDUT@};
wire [NO-1:0] gold_o  = {@CATGOLD@};
wire [NO-1:0] diff    = dut_o ^ gold_o;
wire          correct = (diff === '0);
```

A mismatch prints the offending vector, and the run ends in `$fatal`, so the simulator exits
non-zero and the Makefile turns that into a build failure. A passing testbench prints exactly one
line:

```
[PASS] @EXAMPLEMOD@ : @EXAMPLEVEC@/@EXAMPLEVEC@ vectors match
```

## Where the gold comes from

The gold model is **not** derived from the Verilog being tested. For every standard-cell instance,
the generator takes that cell's `function` attribute out of the PDK Liberty file (`@LIB@`) and
emits one continuous assign, substituting the formal pins with the gold name of the connected net
(a primary input keeps its own name, anything else becomes `g_<net>`):

```systemverilog
@EXAMPLEGOLD@
```

Gold signals therefore never read a DUT signal. Only `@NETLIST@`'s *wiring* is shared between the
two models; the cell semantics come from an independent source.

### Why not `sp2bool`?

The container ships lctime's `sp2bool`, which derives boolean functions straight from a transistor
netlist — the obvious oracle. It does not work on this PDK:

* `lctime/lccommon/net_util.py::get_channel_type()` calls a device NMOS only if its model name
  *starts with* `n`. IHP's models are `sg13_lv_nmos` / `sg13_lv_pmos`, so every transistor is
  treated as a PMOS and even `sg13g2_inv_1` comes out as `Y = True`.
* With the model names shimmed to `nmos_lv`/`pmos_lv`, it still mis-solves the deeper series
  stacks: `sg13g2_nand3_1`, `sg13g2_nand4_1` and `sg13g2_nor3_1` (3 of the cells used here)
  come back as constant `True`/`False`.

The Liberty functions used instead were cross-checked against a direct transistor-network solve of
`sg13g2_stdcell.cdl` (union-find connectivity to VDD/VSS per input vector) and agree for every cell
used by `@NETLIST@`.

The generator, its command-line arguments and the checks it enforces are documented in
[`../README.md`](../README.md).

## The Makefile

| Target | What it does |
| --- | --- |
| `help` | list the targets (default target) |
| `verilator` | build and run every testbench with Verilator, then report pass/fail |
| `icarus` | build and run every testbench with Icarus Verilog, then report pass/fail |
| `all` | `verilator` then `icarus` |
| `nospec` | build only the specify-stripped cell models under `build/nospec/` (see [Notes](#notes)) |
| `clean` | remove `build/` |

The paths the generator was given are baked in as overridable variables:

| Variable | Value here | Meaning |
| --- | --- | --- |
| `NETLIST` | `@NETLISTREL@` | the netlist under test |
| `CELL_SRC_IN` | `@CELLSRCLIST@` | simulation models for the standard cells |
| `VERILATOR_FLAGS` | `--binary --timing -Wno-TIMESCALEMOD -Wno-DECLFILENAME` | |
| `IVERILOG_FLAGS` | `-g2012` | |
| `VCD` | unset | set to `1` to dump waveforms (see below) |

Override any of them on the command line, e.g.
`make all CELL_SRC_IN=/path/to/other_models.v`.

### Waveforms

Off by default. Build with `VCD=1` and each testbench dumps its full hierarchy:

```bash
make verilator VCD=1     # -> build/vlt/<tb>/<tb>.vcd
make icarus    VCD=1     # -> build/icarus/<tb>.vcd
```

`VCD=1` adds `+define+VCD --trace` for Verilator and `-DVCD` for Icarus, which enables the
`$dumpfile`/`$dumpvars` block in each testbench. Since the stimulus is a `#1`-per-vector sweep,
vector *n* sits at time *n+1* ns, and `diff`/`correct` show exactly where a mismatch occurs.
Note that a run is cached by its build directory, so switch `VCD` and the testbenches are rebuilt.

`verilator` and `icarus` keep going after a failing testbench so one run reports every problem, and
exit non-zero if any of them failed. Per-testbench compile and run logs are left in
`build/vlt/` and `build/icarus/`.

## Modules covered

| Testbench | Inputs | Outputs | Vectors |
| --- | --- | --- | --- |
@MODTABLE@

## Notes

* These testbenches check **function only**, not timing. The Makefile therefore builds
  `build/sg13g2_stdcell_nospec.v` — the PDK cell models with their `specify` blocks stripped
  (`make nospec`). That leaves zero-delay gate primitives and also silences Icarus's
  `sorry: ifnone with an edge-sensitive path is not supported`. The `#1` each testbench waits
  between driving a vector and sampling is far longer than the (zero) gate delays.
* Verilator needs `--timing` because of that `#1`, and is run with `--binary`.
* Verilator is 2-state, Icarus 4-state. Every input is driven to a hard 0 or 1 on every vector and
  the netlists are combinational, so no net is ever X and the two agree.
"""


# --------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------


def fill(template: str, **tokens: str) -> str:
    """Substitute @TOKEN@ placeholders. Used instead of str.format because these
    templates are full of literal braces (make, awk, SystemVerilog concatenations)."""
    out = template
    for key, val in tokens.items():
        out = out.replace(f"@{key.upper()}@", val)
    left = re.findall(r"@[A-Z_]+@", out)
    if left:
        raise GenError(f"unsubstituted template tokens: {sorted(set(left))}")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate exhaustive Verilator/Icarus testbenches for a std-cell netlist.",
        epilog="All library paths are explicit arguments so the tool is not tied to any one PDK.",
    )
    ap.add_argument("netlist", type=Path, help="structural Verilog netlist (e.g. aion_cells.v)")
    ap.add_argument(
        "--lib",
        type=Path,
        required=True,
        metavar="FILE",
        help="Liberty file whose 'function' attributes are the gold oracle (required)",
    )
    ap.add_argument(
        "--cell-verilog",
        type=Path,
        action="append",
        default=[],
        metavar="FILE",
        help="simulation model for the standard cells, baked into the generated Makefile; "
        "repeat for several files (required unless --no-makefile)",
    )
    ap.add_argument(
        "-o",
        "--outdir",
        type=Path,
        default=None,
        metavar="DIR",
        help="output directory (default: <netlist dir>/tb)",
    )
    ap.add_argument(
        "--max-inputs",
        type=int,
        default=16,
        metavar="N",
        help="refuse modules with more inputs than this (default: 16)",
    )
    ap.add_argument(
        "--no-strip-specify",
        dest="strip_specify",
        action="store_false",
        help="compile the cell models as-is instead of stripping their 'specify' blocks",
    )
    ap.add_argument(
        "--no-makefile",
        action="store_true",
        help="emit only the testbenches and gold_functions.md (no Makefile, no README.md)",
    )
    args = ap.parse_args(argv)

    netlist: Path = args.netlist
    if not netlist.is_file():
        raise GenError(f"netlist not found: {netlist}")

    lib_path: Path = args.lib
    if not lib_path.is_file():
        raise GenError(f"Liberty file not found: {lib_path}")

    cell_v: list[Path] = list(args.cell_verilog)
    if not args.no_makefile and not cell_v:
        raise GenError(
            "--cell-verilog is required to generate the Makefile: the testbenches instantiate "
            "the standard cells, so the simulators need their models. Pass it once per file, "
            "or use --no-makefile."
        )
    for f in cell_v:
        if not f.is_file():
            raise GenError(f"cell Verilog model not found: {f}")

    outdir: Path = args.outdir or netlist.parent / "tb"
    script_name = f"scripts/{Path(__file__).name}"

    modules = parse_netlist(netlist)
    used_cells = {inst.cell for m in modules for inst in m.instances}
    lib = parse_liberty(lib_path, used_cells)

    models: list[GoldModel] = []
    tables: dict[str, dict[str, list[int]]] = {}
    for mod in modules:
        if len(mod.inputs) > args.max_inputs:
            raise GenError(
                f"module '{mod.name}' has {len(mod.inputs)} inputs, above --max-inputs "
                f"{args.max_inputs}; exhaustive simulation would need {2 ** len(mod.inputs)} vectors"
            )
        gm = build_gold(mod, lib)
        models.append(gm)
        tables[mod.name] = gold_truth_table(gm)

    outdir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for gm in models:
        path = outdir / f"tb_{gm.module.name}.sv"
        path.write_text(emit_tb(gm, script_name, netlist.name, lib_path.name))
        written.append(path)

    report = outdir / "gold_functions.md"
    report.write_text(emit_report(models, tables, script_name, netlist.name, lib_path.name))
    written.append(report)

    if not args.no_makefile:
        netlist_rel = os.path.relpath(netlist.resolve(), outdir.resolve())
        cell_abs = [str(f.resolve()) for f in cell_v]
        mk = outdir / "Makefile"
        mk.write_text(
            fill(
                MAKEFILE_TEMPLATE,
                script=script_name,
                netlist=netlist.name,
                netlistrel=netlist_rel,
                cellsrc=" ".join(cell_abs),
                stripblock=STRIP_BLOCK if args.strip_specify else NO_STRIP_BLOCK,
                tblist=" \\\n".join(f"\ttb_{gm.module.name}" for gm in models),
            )
        )
        written.append(mk)

        gencmd = " \\\n    ".join(
            [f"{Path(__file__).name} {netlist}", f"--lib {lib_path}"]
            + [f"--cell-verilog {f}" for f in cell_v]
            + ([] if args.strip_specify else ["--no-strip-specify"])
        )
        example = models[0]
        rd = outdir / "README.md"
        rd.write_text(
            fill(
                README_TEMPLATE,
                script=script_name,
                scriptbase=Path(__file__).name,
                netlist=netlist.name,
                netlistrel=netlist_rel,
                lib=lib_path.name,
                cellsrclist=" ".join(cell_abs),
                gencmd=gencmd,
                ntb=str(len(models)),
                nvec=str(sum(2 ** len(gm.module.inputs) for gm in models)),
                catdut=", ".join(reversed(example.module.outputs)),
                catgold=", ".join(example.gold_name(o) for o in reversed(example.module.outputs)),
                examplemod=example.module.name,
                examplevec=str(2 ** len(example.module.inputs)),
                examplegold="\n".join(
                    f"assign {example.gold_name(ga.net)} = {gold_sv_expr(example, ga)};"
                    f"  // {ga.inst.name} {ga.inst.cell}: {ga.out_pin} = {ga.lib_func}"
                    for ga in example.assigns
                ),
                modtable="\n".join(
                    f"| `tb_{gm.module.name}.sv` | {len(gm.module.inputs)} | "
                    f"{len(gm.module.outputs)} | {2 ** len(gm.module.inputs)} |"
                    for gm in models
                ),
            )
        )
        written.append(rd)

    print(f"Liberty oracle : {lib_path}")
    for f in cell_v:
        print(f"Cell models    : {f}")
    print(f"Netlist        : {netlist}  ({len(modules)} modules, {len(used_cells)} distinct cells)")
    print(f"Output         : {outdir}")
    for gm in models:
        print(
            f"  tb_{gm.module.name:<32} {len(gm.module.inputs)} in, "
            f"{len(gm.module.outputs)} out, {2 ** len(gm.module.inputs)} vectors"
        )
    print(f"Wrote {len(written)} files.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except GenError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
