#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Davide Schiavone
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""
Self-contained generator for the 4-bit current-steering DAC layout (Magic TCL), ihp-sg13g2.

Run (repo root, in the container):
    python3 macros/dac/scripts/gen_dac_layout.py dac4 layout > layout/_dac4.tcl
    cd layout && magic -dnull -noconsole -rcfile <magicrc> _dac4.tcl
(the Makefile `gen-layout` target does this).

Approach (validated headless; see macros/dac/DAC_LAYOUT.md):
  * Devices: PDK gencells `magic::gencell_makecell sg13g2::sg13_lv_{n,p}mos ... guard 1`
    (each device self-contained: own nwell/psub tap ring + B port).
  * Placement: `getcell <dev> child 0 0 parent <x_iu> <y_iu>` -> device CENTRE at (x,y).
    parent coords are in INTERNAL UNITS (1 um = 200 iu).
  * Routing: each terminal comes up through an M1->M2->M3->M4 via stack; nets route on
    M3 horizontal tracks (unique y per net) + M4 vertical jogs. metal5 is never used.
  * Binary weights = replicated UNIT devices (the gencell `m` only arrays unconnected
    fingers); netgen merges parallels by summing W, so the LVS reference (dac4_lay.spice)
    uses explicit units too. The ideal reference current is off-chip: `vpcs` is a pin.

Units: layout coordinates are in MICRONS.
"""
import sys

UM_TO_IU = 200.0       # getcell parent refpoint is in internal units (1 um = 200 iu)

# Device port offsets (um, rel. to device centre) + FULL bbox half-extents (incl. guard
# halo), probed from the guard=1 gencells.
DEVICES = {
    "pmos_1_0p13":   dict(kind="pmos", w=1.0, l=0.13, fhw=1.225, fhh=1.55,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "nmos_0p5_0p13": dict(kind="nmos", w=0.5, l=0.13, fhw=1.225, fhh=1.30,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.47), B=(0.0, -0.84))),
    "nmos_1_0p13":   dict(kind="nmos", w=1.0, l=0.13, fhw=1.225, fhh=1.55,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "nmos_1_0p5":    dict(kind="nmos", w=1.0, l=0.5, fhw=1.41, fhh=1.55,
                          ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    # DAC current-source unit (Mpref / Msrc), long L for matching
    "pmos_2_1":      dict(kind="pmos", w=2.0, l=1.0, fhw=1.66, fhh=2.05,
                          ports=dict(D=(-0.69, 0.0), S=(0.69, 0.0), G=(0.0, 1.22), B=(0.0, -1.59))),
}

WIRE_W = 0.20
VIA_S = 0.30


class Layout:
    """Accumulates Magic TCL for one cell (device factory + M3/M4 over-the-cell router)."""

    def __init__(self, cell):
        self.cell = cell
        self.devseen = {}
        self.pre = []
        self.devlines = []
        self.lines = []
        self.insts = {}
        self.ports = []

    def _emit(self, s):
        self.lines.append(s)

    def header(self):
        self.pre += ["# AUTO-GENERATED by gen_dac_layout.py — do not edit by hand.",
                     "gds rescale false", "snap internal"]

    def make_device(self, devkey):
        if devkey in self.devseen:
            return
        d = DEVICES[devkey]
        var = "dev_" + devkey
        gc = "sg13_lv_pmos" if d["kind"] == "pmos" else "sg13_lv_nmos"
        self.devlines.append(f"set {var} [magic::gencell_makecell sg13g2::{gc} "
                             f"w {d['w']} l {d['l']} ng 1 m 1 guard 1]")
        self.devseen[devkey] = var

    def begin_cell(self):
        pass

    def place(self, inst, devkey, cx, cy):
        self.make_device(devkey)
        var = self.devseen[devkey]
        self._emit(f"getcell ${var} child 0 0 parent {round(cx * UM_TO_IU)} {round(cy * UM_TO_IU)}")
        self._emit(f"identify {inst}")
        self.insts[inst] = (devkey, cx, cy)

    def place_row(self, specs, gap=0.7, y=0.0):
        cx, prev_fhw = 0.0, None
        for inst, devkey in specs:
            fhw = DEVICES[devkey]["fhw"]
            if prev_fhw is not None:
                cx += prev_fhw + gap + fhw
            self.place(inst, devkey, cx, y)
            prev_fhw = fhw

    def port_xy(self, inst, term):
        devkey, cx, cy = self.insts[inst]
        dx, dy = DEVICES[devkey]["ports"][term]
        return (cx + dx, cy + dy)

    def rect(self, layer, x0, y0, x1, y1):
        x0, x1 = sorted((x0, x1))
        y0, y1 = sorted((y0, y1))
        self._emit(f"box {x0:.3f}um {y0:.3f}um {x1:.3f}um {y1:.3f}um")
        self._emit(f"paint {layer}")

    def via_stack(self, x, y, s=VIA_S):
        h = s / 2.0
        for lyr in ("m1", "via1", "via2", "via3"):
            self.rect(lyr, x - h, y - h, x + h, y + h)

    def vwire(self, layer, x, y0, y1, w=WIRE_W):
        self.rect(layer, x - w / 2, y0, x + w / 2, y1)

    def hwire(self, layer, y, x0, x1, w=WIRE_W):
        self.rect(layer, x0, y - w / 2, x1, y + w / 2)

    def via3_at(self, x, y, s=VIA_S):
        h = s / 2.0
        self.rect("via3", x - h, y - h, x + h, y + h)

    def route_net(self, net, terms, track_y, mkport=False, port_layer="m3"):
        pts = [self.port_xy(i, t) for (i, t) in terms]
        xs = [p[0] for p in pts]
        if len(pts) > 1:
            self.hwire("m3", track_y, min(xs) - 0.1, max(xs) + 0.1)
        for (px, py) in pts:
            self.via_stack(px, py)
            self.vwire("m4", px, py, track_y)
            self.via3_at(px, track_y)
        if len(pts) == 1:
            px, py = pts[0]
            self.hwire("m3", track_y, px - 0.15, px + 0.15)
        if mkport:
            self.ports.append((net, port_layer, xs[0], track_y))

    def finish(self, outdir):
        for i, (net, layer, x, y) in enumerate(self.ports):
            self._emit(f"box {x:.3f}um {y:.3f}um {x:.3f}um {y:.3f}um")
            self._emit(f"label {net} center {layer}")
            self._emit(f"port make {i + 1}")
        self._emit("select top cell")
        self._emit(f"save {self.cell}")
        self._emit("writeall force")
        self._emit(f"gds write {self.cell}.gds")
        self._emit(f'puts "GEN_DONE {self.cell}"')
        self._emit("quit -noprompt")

    def tcl(self):
        return "\n".join(self.pre + self.devlines
                         + [f"cellname create {self.cell}", f"load {self.cell}"] + self.lines) + "\n"


def build_dac4(outdir, mkport=True):
    """dac4 VDD VSS b0 b1 b2 b3 iout vpcs — current-steering DAC core (ideal ref off-chip)."""
    lo = Layout("dac4")
    lo.header()
    lo.begin_cell()

    # Row: reference mirror | all unit current sources (grouped for matching) |
    #      all 'to' steer nmos | all 'do' steer nmos | bit inverters | dump diode.
    row = [("Mpref", "pmos_2_1")]
    src, to, do, inv = [], [], [], []
    for i in range(4):
        for j in range(1 << i):
            src.append((f"Msrc{i}_{j}", "pmos_2_1"))
            to.append((f"Mto{i}_{j}", "nmos_1_0p13"))
            do.append((f"Mdo{i}_{j}", "nmos_1_0p13"))
        inv += [(f"Minvp{i}", "pmos_1_0p13"), (f"Minvn{i}", "nmos_0p5_0p13")]
    row += src + to + do + inv + [("Mdump", "nmos_1_0p5")]
    lo.place_row(row, gap=0.7)

    nets = {}

    def add(inst, **conn):
        for term, net in conn.items():
            nets.setdefault(net, []).append((inst, term))

    add("Mpref", D="vpcs", G="vpcs", S="VDD", B="VDD")
    add("Mdump", D="ndump", G="ndump", S="VSS", B="VSS")
    for i in range(4):
        for j in range(1 << i):
            add(f"Msrc{i}_{j}", D=f"cs{i}", G="vpcs",   S="VDD",    B="VDD")
            add(f"Mto{i}_{j}",  D="iout",  G=f"b{i}",   S=f"cs{i}",  B="VSS")
            add(f"Mdo{i}_{j}",  D="ndump", G=f"b{i}b",  S=f"cs{i}",  B="VSS")
        add(f"Minvp{i}", D=f"b{i}b", G=f"b{i}", S="VDD", B="VDD")
        add(f"Minvn{i}", D=f"b{i}b", G=f"b{i}", S="VSS", B="VSS")

    ports = {"VDD", "VSS", "vpcs", "iout", "b0", "b1", "b2", "b3"}
    lo.route_net("VDD", nets.pop("VDD"), track_y=-2.7, mkport=mkport)
    lo.route_net("VSS", nets.pop("VSS"), track_y=-3.3, mkport=mkport)
    order = ["vpcs", "iout", "ndump", "cs0", "cs1", "cs2", "cs3",
             "b0", "b1", "b2", "b3", "b0b", "b1b", "b2b", "b3b"]
    y = 2.4
    for net in order:
        lo.route_net(net, nets.pop(net), track_y=y, mkport=(mkport and net in ports))
        y += 0.5
    assert not nets, f"unrouted nets: {list(nets)}"

    lo.finish(outdir)
    return lo


BUILDERS = {"dac4": build_dac4}

if __name__ == "__main__":
    cell = sys.argv[1] if len(sys.argv) > 1 else "dac4"
    outdir = sys.argv[2] if len(sys.argv) > 2 else "layout"
    sys.stdout.write(BUILDERS[cell](outdir, mkport="--noport" not in sys.argv).tcl())
