#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Davide Schiavone
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""
Self-contained generator for the ring-oscillator layout cells (Magic TCL), ihp-sg13g2.

Cells:
  cs_stage         — one current-starved inverter stage (4 FETs), the matched leaf.
  ring_oscillator  — full RO: bias gen + 5 stages + output buffer, COMPACT routing.

Run (repo root, in the container):
    python3 macros/ring_oscillator/scripts/gen_ro_layout.py <cell> layout > layout/_<cell>.tcl
    cd layout && magic -dnull -noconsole -rcfile <magicrc> _<cell>.tcl
(the Makefile `gen-layout` target does this).

Approach (validated headless; see macros/ring_oscillator/RING_OSCILLATOR_LAYOUT.md):
  * Devices: PDK gencells `magic::gencell_makecell sg13g2::sg13_lv_{n,p}mos ... guard 1`.
  * Placement: `getcell <dev> child 0 0 parent <x_iu> <y_iu>` -> centre at (x,y); parent
    coords in INTERNAL UNITS (1 um = 200 iu).
  * Routing TWO ways:
      - GLOBAL DC nets (vbp, ibias, VDD, VSS): M1->M2->M3->M4 stacks + M4 jogs + M3 tracks
        high above the row (route_net). Their parasitics don't set the oscillation freq.
      - LOCAL signal nets (ring nodes n1..n5, internal pp/nn, buffer b1/clk): short
        M1->M2->M3 stacks + M3-only wiring on LOW tracks packed by an x-interval allocator
        (route_local). This avoids the long parallel-track field + M4 jogs that otherwise
        dump ~60 fF onto every ring node and crush the frequency (see DAC/RO PEX notes).
  * Stage devices are CLUSTERED per stage and stages abut, so each ring node spans only
    ~one stage. metal5 is never used.

Units: layout coordinates are in MICRONS.
"""
import sys

UM_TO_IU = 200.0

DEVICES = {
    "pmos_2_0p5":    dict(kind="pmos", w=2.0, l=0.5, fhw=1.41, fhh=2.05,
                          ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 1.22), B=(0.0, -1.59))),
    "pmos_1_0p13":   dict(kind="pmos", w=1.0, l=0.13, fhw=1.225, fhh=1.55,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "nmos_0p5_0p13": dict(kind="nmos", w=0.5, l=0.13, fhw=1.225, fhh=1.30,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.47), B=(0.0, -0.84))),
    "nmos_1_0p5":    dict(kind="nmos", w=1.0, l=0.5, fhw=1.41, fhh=1.55,
                          ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "pmos_2_0p13":   dict(kind="pmos", w=2.0, l=0.13, fhw=1.225, fhh=2.05,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 1.22), B=(0.0, -1.59))),
    "nmos_1_0p13":   dict(kind="nmos", w=1.0, l=0.13, fhw=1.225, fhh=1.55,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
}

WIRE_W = 0.20
VIA_S = 0.30


class Layout:
    def __init__(self, cell):
        self.cell = cell
        self.devseen = {}
        self.pre = []
        self.devlines = []
        self.lines = []
        self.insts = {}
        self.ports = []
        self.local_tracks = []   # list of (y, [ (x0,x1), ... ]) for the local M3 allocator

    def _emit(self, s):
        self.lines.append(s)

    def header(self):
        self.pre += ["# AUTO-GENERATED by gen_ro_layout.py — do not edit by hand.",
                     "gds rescale false", "snap internal"]

    def make_device(self, devkey):
        if devkey in self.devseen:
            return
        d = DEVICES[devkey]
        var = "dev_" + devkey
        gc = "sg13_lv_pmos" if d["kind"] == "pmos" else "sg13_lv_nmos"
        self.devlines.append(f"set {var} [magic::gencell_makecell sg13g2::{gc} "
                             f"w {d['w']} l {d['l']} ng 1 m 1 guard 1]")
        self.devseen[devkey] = var

    def begin_cell(self):
        pass

    def place(self, inst, devkey, cx, cy):
        self.make_device(devkey)
        var = self.devseen[devkey]
        self._emit(f"getcell ${var} child 0 0 parent {round(cx * UM_TO_IU)} {round(cy * UM_TO_IU)}")
        self._emit(f"identify {inst}")
        self.insts[inst] = (devkey, cx, cy)

    def place_row(self, specs, gap=0.7, y=0.0):
        cx, prev_fhw = 0.0, None
        for inst, devkey in specs:
            fhw = DEVICES[devkey]["fhw"]
            if prev_fhw is not None:
                cx += prev_fhw + gap + fhw
            self.place(inst, devkey, cx, y)
            prev_fhw = fhw

    def port_xy(self, inst, term):
        devkey, cx, cy = self.insts[inst]
        dx, dy = DEVICES[devkey]["ports"][term]
        return (cx + dx, cy + dy)

    # ---- painting ----
    def rect(self, layer, x0, y0, x1, y1):
        x0, x1 = sorted((x0, x1))
        y0, y1 = sorted((y0, y1))
        self._emit(f"box {x0:.3f}um {y0:.3f}um {x1:.3f}um {y1:.3f}um")
        self._emit(f"paint {layer}")

    def via_stack(self, x, y, top="m4", s=VIA_S):
        h = s / 2.0
        layers = ("m1", "via1", "via2", "via3") if top == "m4" else ("m1", "via1", "via2")
        for lyr in layers:
            self.rect(lyr, x - h, y - h, x + h, y + h)

    def vwire(self, layer, x, y0, y1, w=WIRE_W):
        self.rect(layer, x - w / 2, y0, x + w / 2, y1)

    def hwire(self, layer, y, x0, x1, w=WIRE_W):
        self.rect(layer, x0, y - w / 2, x1, y + w / 2)

    def via3_at(self, x, y, s=VIA_S):
        h = s / 2.0
        self.rect("via3", x - h, y - h, x + h, y + h)

    # ---- global net router (M4 jogs + high M3 track) ----
    def route_net(self, net, terms, track_y, mkport=False, port_layer="m3"):
        pts = [self.port_xy(i, t) for (i, t) in terms]
        xs = [p[0] for p in pts]
        if len(pts) > 1:
            self.hwire("m3", track_y, min(xs) - 0.1, max(xs) + 0.1)
        for (px, py) in pts:
            self.via_stack(px, py, top="m4")
            self.vwire("m4", px, py, track_y)
            self.via3_at(px, track_y)
        if len(pts) == 1:
            px, py = pts[0]
            self.hwire("m3", track_y, px - 0.15, px + 0.15)
        if mkport:
            self.ports.append((net, port_layer, xs[0], track_y))

    # ---- local net router (M3-only, short, packed onto low tracks) ----
    def _alloc_local_track(self, x0, x1, base=2.3, pitch=0.55, margin=0.45):
        for (y, ivals) in self.local_tracks:
            if all(x1 + margin < a or x0 - margin > b for (a, b) in ivals):
                ivals.append((x0, x1))
                return y
        y = base + len(self.local_tracks) * pitch
        self.local_tracks.append((y, [(x0, x1)]))
        return y

    def route_local(self, net, terms, mkport=False, port_layer="m3"):
        """Like route_net (M4 vertical jogs at unique x + M3 horizontal track at unique y,
        meeting only at intended via3 -> short-safe), but the track is packed onto a LOW
        track by the x-interval allocator. Low + short + per-stage-clustered => the long
        M4 jogs and the dense parallel-track field that loaded the ring nodes are gone."""
        pts = [self.port_xy(i, t) for (i, t) in terms]
        xs = [p[0] for p in pts]
        ty = self._alloc_local_track(min(xs), max(xs))
        if len(pts) > 1:
            self.hwire("m3", ty, min(xs) - 0.1, max(xs) + 0.1)
        for (px, py) in pts:
            self.via_stack(px, py, top="m4")          # M1->M2->M3->M4 at the terminal
            self.vwire("m4", px, py, ty)              # short M4 jog up to the low track
            self.via3_at(px, ty)                      # M4 -> M3 at the track
        if len(pts) == 1:
            px, py = pts[0]
            self.hwire("m3", ty, px - 0.15, px + 0.15)
        if mkport:
            self.ports.append((net, port_layer, xs[0], ty))

    def finish(self, outdir):
        for i, (net, layer, x, y) in enumerate(self.ports):
            self._emit(f"box {x:.3f}um {y:.3f}um {x:.3f}um {y:.3f}um")
            self._emit(f"label {net} center {layer}")
            self._emit(f"port make {i + 1}")
        self._emit("select top cell")
        self._emit(f"save {self.cell}")
        self._emit("writeall force")
        self._emit(f"gds write {self.cell}.gds")
        self._emit(f'puts "GEN_DONE {self.cell}"')
        self._emit("quit -noprompt")

    def tcl(self):
        return "\n".join(self.pre + self.devlines
                         + [f"cellname create {self.cell}", f"load {self.cell}"] + self.lines) + "\n"


# ---------------------------------------------------------------------------------------
def build_cs_stage(outdir, mkport=True):
    """cs_stage VDD VSS vbp vbn in out (the matched leaf, simple over-the-cell routing)."""
    lo = Layout("cs_stage")
    lo.header()
    lo.begin_cell()
    lo.place_row([("Mcp", "pmos_2_0p5"), ("Mp", "pmos_1_0p13"),
                  ("Mn", "nmos_0p5_0p13"), ("Mcn", "nmos_1_0p5")], gap=0.7)
    lo.route_net("out", [("Mp", "D"), ("Mn", "D")], track_y=2.2, mkport=mkport)
    lo.route_net("pp",  [("Mcp", "D"), ("Mp", "S")], track_y=2.7)
    lo.route_net("nn",  [("Mn", "S"), ("Mcn", "D")], track_y=3.2)
    lo.route_net("in",  [("Mp", "G"), ("Mn", "G")], track_y=3.7, mkport=mkport)
    lo.route_net("vbp", [("Mcp", "G")], track_y=4.2, mkport=mkport)
    lo.route_net("vbn", [("Mcn", "G")], track_y=4.7, mkport=mkport)
    lo.route_net("VDD", [("Mcp", "S"), ("Mcp", "B"), ("Mp", "B")], track_y=-2.7, mkport=mkport)
    lo.route_net("VSS", [("Mcn", "S"), ("Mcn", "B"), ("Mn", "B")], track_y=-3.2, mkport=mkport)
    lo.finish(outdir)
    return lo


def build_ring_oscillator(outdir, mkport=True):
    """Full current-starved ring oscillator, COMPACT: bias + 5 clustered stages + buffer.
       Ports: VDD VSS ibias clk."""
    lo = Layout("ring_oscillator")
    lo.header()
    lo.begin_cell()

    # device row: bias | stage1..5 (each clustered: Mcp Mp Mn Mcn) | buffer
    row = [("Mbn", "nmos_1_0p5"), ("Mmir", "nmos_1_0p5"), ("Mbp", "pmos_2_0p5")]
    for i in range(1, 6):
        row += [(f"Mcp{i}", "pmos_2_0p5"), (f"Mp{i}", "pmos_1_0p13"),
                (f"Mn{i}", "nmos_0p5_0p13"), (f"Mcn{i}", "nmos_1_0p5")]
    row += [("Mb1p", "pmos_1_0p13"), ("Mb1n", "nmos_0p5_0p13"),
            ("Mb2p", "pmos_2_0p13"), ("Mb2n", "nmos_1_0p13")]
    lo.place_row(row, gap=0.7)

    nets = {}

    def add(inst, **conn):
        for term, net in conn.items():
            nets.setdefault(net, []).append((inst, term))

    add("Mbn",  D="ibias", G="ibias", S="VSS", B="VSS")
    add("Mmir", D="vbp",   G="ibias", S="VSS", B="VSS")
    add("Mbp",  D="vbp",   G="vbp",   S="VDD", B="VDD")
    nin = {1: "n5", 2: "n1", 3: "n2", 4: "n3", 5: "n4"}
    for i in range(1, 6):
        add(f"Mcp{i}", D=f"pp{i}", G="vbp",   S="VDD",    B="VDD")
        add(f"Mp{i}",  D=f"n{i}",  G=nin[i],  S=f"pp{i}",  B="VDD")
        add(f"Mn{i}",  D=f"n{i}",  G=nin[i],  S=f"nn{i}",  B="VSS")
        add(f"Mcn{i}", D=f"nn{i}", G="ibias", S="VSS",     B="VSS")
    add("Mb1p", D="b1",  G="n5", S="VDD", B="VDD")
    add("Mb1n", D="b1",  G="n5", S="VSS", B="VSS")
    add("Mb2p", D="clk", G="b1", S="VDD", B="VDD")
    add("Mb2n", D="clk", G="b1", S="VSS", B="VSS")

    # GLOBAL DC nets on the upper M4 tracks (their parasitics don't set the frequency)
    ports = {"VDD", "VSS", "ibias", "clk"}
    lo.route_net("VDD",   nets.pop("VDD"),   track_y=-2.7, mkport=mkport)
    lo.route_net("VSS",   nets.pop("VSS"),   track_y=-3.3, mkport=mkport)
    lo.route_net("vbp",   nets.pop("vbp"),   track_y=8.0)
    lo.route_net("ibias", nets.pop("ibias"), track_y=8.6, mkport=mkport)
    # LOCAL signal nets (ring nodes, internal pp/nn, buffer) on packed low M3 tracks
    for net in ["n1", "n2", "n3", "n4", "n5", "b1",
                "pp1", "pp2", "pp3", "pp4", "pp5",
                "nn1", "nn2", "nn3", "nn4", "nn5"]:
        lo.route_local(net, nets.pop(net))
    lo.route_local("clk", nets.pop("clk"), mkport=mkport)
    assert not nets, f"unrouted nets: {list(nets)}"

    lo.finish(outdir)
    return lo


BUILDERS = {"cs_stage": build_cs_stage, "ring_oscillator": build_ring_oscillator}

if __name__ == "__main__":
    cell = sys.argv[1] if len(sys.argv) > 1 else "ring_oscillator"
    outdir = sys.argv[2] if len(sys.argv) > 2 else "layout"
    sys.stdout.write(BUILDERS[cell](outdir, mkport="--noport" not in sys.argv).tcl())
