#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Davide Schiavone
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""
Self-contained generator for the ring-oscillator layout cells (Magic TCL), ihp-sg13g2.

Cells:
  cs_stage         — one current-starved inverter stage (4 FETs), the matched leaf.
  ring_oscillator  — full RO: bias gen + 5 stages + output buffer, COMPACT routing.

Run (repo root, in the container):
    python3 macros/ring_oscillator/scripts/gen_ro_layout.py <cell> layout > layout/_<cell>.tcl
    cd layout && magic -dnull -noconsole -rcfile <magicrc> _<cell>.tcl
(the Makefile `gen-layout` target does this).

Approach (validated headless; see macros/ring_oscillator/RING_OSCILLATOR_LAYOUT.md):
  * Devices: PDK gencells `magic::gencell_makecell sg13g2::sg13_lv_{n,p}mos ... guard 1`.
  * Placement: `getcell <dev> child 0 0 parent <x_iu> <y_iu>` -> centre at (x,y); parent
    coords in INTERNAL UNITS (1 um = 200 iu).
  * Routing TWO ways:
      - GLOBAL DC nets (vbp, ibias, VDD, VSS): M1->M2->M3->M4 stacks + M4 jogs + M3 tracks
        high above the row (route_net). Their parasitics don't set the oscillation freq.
      - LOCAL signal nets (ring nodes n1..n5, internal pp/nn, buffer b1/clk): short
        M1->M2->M3 stacks + M3-only wiring on LOW tracks packed by an x-interval allocator
        (route_local). This avoids the long parallel-track field + M4 jogs that otherwise
        dump ~60 fF onto every ring node and crush the frequency (see DAC/RO PEX notes).
  * Stage devices are CLUSTERED per stage and stages abut, so each ring node spans only
    ~one stage. metal5 is never used.

Units: layout coordinates are in MICRONS.
"""
import sys

UM_TO_IU = 200.0

DEVICES = {
    "pmos_2_0p5":    dict(kind="pmos", w=2.0, l=0.5, fhw=1.41, fhh=2.05,
                          ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 1.22), B=(0.0, -1.59))),
    "pmos_1_0p13":   dict(kind="pmos", w=1.0, l=0.13, fhw=1.225, fhh=1.55,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "nmos_0p5_0p13": dict(kind="nmos", w=0.5, l=0.13, fhw=1.225, fhh=1.30,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.47), B=(0.0, -0.84))),
    "nmos_1_0p5":    dict(kind="nmos", w=1.0, l=0.5, fhw=1.41, fhh=1.55,
                          ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "pmos_2_0p13":   dict(kind="pmos", w=2.0, l=0.13, fhw=1.225, fhh=2.05,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 1.22), B=(0.0, -1.59))),
    "nmos_1_0p13":   dict(kind="nmos", w=1.0, l=0.13, fhw=1.225, fhh=1.55,
                          ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
}

WIRE_W = 0.20
VIA_S = 0.30


class Layout:
    def __init__(self, cell):
        self.cell = cell
        self.devseen = {}
        self.pre = []
        self.devlines = []
        self.lines = []
        self.insts = {}
        self.ports = []
        self.netlabels = []      # (net, layer, x, y) plain labels (name a net, not a port)
        self.local_tracks = []   # list of (y, [ (x0,x1), ... ]) for the local M3 allocator

    def _emit(self, s):
        self.lines.append(s)

    def header(self):
        self.pre += ["# AUTO-GENERATED by gen_ro_layout.py — do not edit by hand.",
                     "gds rescale false", "snap internal"]

    def make_device(self, devkey):
        if devkey in self.devseen:
            return
        d = DEVICES[devkey]
        var = "dev_" + devkey
        gc = "sg13_lv_pmos" if d["kind"] == "pmos" else "sg13_lv_nmos"
        self.devlines.append(f"set {var} [magic::gencell_makecell sg13g2::{gc} "
                             f"w {d['w']} l {d['l']} ng 1 m 1 guard 1]")
        self.devseen[devkey] = var

    def begin_cell(self):
        pass

    def place(self, inst, devkey, cx, cy, flipy=False):
        self.make_device(devkey)
        var = self.devseen[devkey]
        self._emit(f"getcell ${var} child 0 0 parent {round(cx * UM_TO_IU)} {round(cy * UM_TO_IU)}")
        self._emit(f"identify {inst}")
        if flipy:
            self._emit(f"select cell {inst}")
            self._emit("upsidedown")   # mirror in y so the gate faces the channel
        self.insts[inst] = (devkey, cx, cy, flipy)

    def place_row(self, specs, gap=0.7, y=0.0):
        cx, prev_fhw = 0.0, None
        for inst, devkey in specs:
            fhw = DEVICES[devkey]["fhw"]
            if prev_fhw is not None:
                cx += prev_fhw + gap + fhw
            self.place(inst, devkey, cx, y)
            prev_fhw = fhw

    def port_xy(self, inst, term):
        devkey, cx, cy, flipy = self.insts[inst]
        dx, dy = DEVICES[devkey]["ports"][term]
        return (cx + dx, cy + (-dy if flipy else dy))

    # ---- painting ----
    def rect(self, layer, x0, y0, x1, y1):
        x0, x1 = sorted((x0, x1))
        y0, y1 = sorted((y0, y1))
        self._emit(f"box {x0:.3f}um {y0:.3f}um {x1:.3f}um {y1:.3f}um")
        self._emit(f"paint {layer}")

    def via_stack(self, x, y, top="m4", s=VIA_S):
        h = s / 2.0
        layers = ("m1", "via1", "via2", "via3") if top == "m4" else ("m1", "via1", "via2")
        for lyr in layers:
            self.rect(lyr, x - h, y - h, x + h, y + h)

    def vwire(self, layer, x, y0, y1, w=WIRE_W):
        self.rect(layer, x - w / 2, y0, x + w / 2, y1)

    def hwire(self, layer, y, x0, x1, w=WIRE_W):
        self.rect(layer, x0, y - w / 2, x1, y + w / 2)

    def via3_at(self, x, y, s=VIA_S):
        h = s / 2.0
        self.rect("via3", x - h, y - h, x + h, y + h)

    def via1_pad(self, x, y, s=VIA_S):
        """M1->M2 contact at a device terminal (so a local M2 wire can attach)."""
        h = s / 2.0
        self.rect("m1", x - h, y - h, x + h, y + h)
        self.rect("via1", x - h, y - h, x + h, y + h)

    def via12_pad(self, x, y, s=VIA_S):
        """M1->M2->M3 contact (for dropping a global M3 rail onto a terminal)."""
        h = s / 2.0
        for lyr in ("m1", "via1", "via2"):
            self.rect(lyr, x - h, y - h, x + h, y + h)

    # ---- global net router (vertical jogs on `top`, horizontal track on M3) ----
    def route_net(self, net, terms, track_y, mkport=False, port_layer="m3", top="m4", w=WIRE_W):
        """top='m4' (default) routes jogs on M4; top='m3' on M3. Two global nets whose
        terminals share an x (e.g. a device's gate and bulk at centre-x) must use
        different `top` layers so their coincident verticals don't short. `w` widens the
        track/jogs — use a wide low-R strap for the VDD/VSS power rails (thin power routing
        leaves kohms of series R that collapses the oscillation)."""
        jog = top
        pts = [self.port_xy(i, t) for (i, t) in terms]
        xs = [p[0] for p in pts]
        if len(pts) > 1:
            self.hwire("m3", track_y, min(xs) - 0.1, max(xs) + 0.1, w=w)
        for (px, py) in pts:
            self.via_stack(px, py, top=top)            # small via (clears centre-x neighbours)
            self.vwire(jog, px, py, track_y)           # thin jog (clears centre-x neighbours)
            if top == "m4":
                self.via3_at(px, track_y)   # M4 jog -> M3 track
        if len(pts) == 1:
            px, py = pts[0]
            self.hwire("m3", track_y, px - 0.15, px + 0.15, w=w)
        if mkport:
            self.ports.append((net, port_layer, xs[0], track_y))

    # ---- local net router (M3-only, short, packed onto low tracks) ----
    def _alloc_local_track(self, x0, x1, base=2.3, pitch=0.55, margin=0.45):
        for (y, ivals) in self.local_tracks:
            if all(x1 + margin < a or x0 - margin > b for (a, b) in ivals):
                ivals.append((x0, x1))
                return y
        y = base + len(self.local_tracks) * pitch
        self.local_tracks.append((y, [(x0, x1)]))
        return y

    def route_ring(self, net, terms, hop_y, mkport=False):
        """Proper 2-layer channel router: a horizontal M2 trunk at hop_y (in the empty
        channel between the P and N rows) and per-column VERTICAL STUBS ON M3. Trunk (M2)
        and stubs (M3) are on different layers, so a stub crossing another net's trunk does
        NOT short — only the net's own via2 connects them. Drain stubs are jogged ~1.3 um
        left into the inter-column gap so they clear the gate stub of the same column (the
        device puts drain and gate only 0.255 um apart). Ring nodes thus become short,
        isolated wires -> the coupling-heavy parallel-track field is gone."""
        pts = [(self.port_xy(i, t), t) for (i, t) in terms]
        xs = [p[0][0] for p in pts]
        # group terminals by x-column
        cols = {}
        for ((px, py), t) in pts:
            cols.setdefault(round(px, 2), []).append((px, py, t))
        via_xs = []
        for xc, members in cols.items():
            is_gate = any(t == "G" for (_, _, t) in members)
            for (mx, my, t) in members:
                self.via12_pad(mx, my)                    # M1->M2->M3 at the terminal
            if is_gate:
                vx = xc                                   # gate stub: M3 vertical at the gate
            else:
                vx = xc - 1.3                             # drain stub: jog left into the gap
                for (mx, my, t) in members:
                    self.hwire("m3", my, vx, mx)          # short M3 jog from drain to vx
            ys = [py for (_, py, _) in members]
            self.vwire("m3", vx, min(ys + [hop_y]), max(ys + [hop_y]))
            via_xs.append(vx)
        # M2 trunk spanning all stub columns + a via2 (M2<->M3) at each stub
        self.hwire("m2", hop_y, min(via_xs) - 0.1, max(via_xs) + 0.1)
        for vx in via_xs:
            self.rect("via2", vx - VIA_S / 2, hop_y - VIA_S / 2, vx + VIA_S / 2, hop_y + VIA_S / 2)
        # non-port net label so the ring node is reachable in sim/PEX (e.g. startup kick)
        self.netlabels.append((net, "m2", min(via_xs) + 0.2, hop_y))
        if mkport:
            self.ports.append((net, "m2", via_xs[0], hop_y))

    def route_local(self, net, terms, mkport=False, port_layer="m3"):
        """Like route_net (M4 vertical jogs at unique x + M3 horizontal track at unique y,
        meeting only at intended via3 -> short-safe), but the track is packed onto a LOW
        track by the x-interval allocator. Low + short + per-stage-clustered => the long
        M4 jogs and the dense parallel-track field that loaded the ring nodes are gone."""
        pts = [self.port_xy(i, t) for (i, t) in terms]
        xs = [p[0] for p in pts]
        ty = self._alloc_local_track(min(xs), max(xs))
        if len(pts) > 1:
            self.hwire("m3", ty, min(xs) - 0.1, max(xs) + 0.1)
        for (px, py) in pts:
            self.via_stack(px, py, top="m4")          # M1->M2->M3->M4 at the terminal
            self.vwire("m4", px, py, ty)              # short M4 jog up to the low track
            self.via3_at(px, ty)                      # M4 -> M3 at the track
        if len(pts) == 1:
            px, py = pts[0]
            self.hwire("m3", ty, px - 0.15, px + 0.15)
        if mkport:
            self.ports.append((net, port_layer, xs[0], ty))

    def finish(self, outdir):
        for i, (net, layer, x, y) in enumerate(self.ports):
            self._emit(f"box {x:.3f}um {y:.3f}um {x:.3f}um {y:.3f}um")
            self._emit(f"label {net} center {layer}")
            self._emit(f"port make {i + 1}")
        # plain net labels (named nets, not ports) for sim/PEX node access
        for (net, layer, x, y) in self.netlabels:
            self._emit(f"box {x:.3f}um {y:.3f}um {x:.3f}um {y:.3f}um")
            self._emit(f"label {net} center {layer}")
        self._emit("select top cell")
        self._emit(f"save {self.cell}")
        self._emit("writeall force")
        self._emit(f"gds write {self.cell}.gds")
        self._emit(f'puts "GEN_DONE {self.cell}"')
        self._emit("quit -noprompt")

    def tcl(self):
        return "\n".join(self.pre + self.devlines
                         + [f"cellname create {self.cell}", f"load {self.cell}"] + self.lines) + "\n"


# ---------------------------------------------------------------------------------------
def build_cs_stage(outdir, mkport=True):
    """cs_stage VDD VSS vbp vbn in out (the matched leaf, simple over-the-cell routing)."""
    lo = Layout("cs_stage")
    lo.header()
    lo.begin_cell()
    lo.place_row([("Mcp", "pmos_2_0p5"), ("Mp", "pmos_1_0p13"),
                  ("Mn", "nmos_0p5_0p13"), ("Mcn", "nmos_1_0p5")], gap=0.7)
    lo.route_net("out", [("Mp", "D"), ("Mn", "D")], track_y=2.2, mkport=mkport)
    lo.route_net("pp",  [("Mcp", "D"), ("Mp", "S")], track_y=2.7)
    lo.route_net("nn",  [("Mn", "S"), ("Mcn", "D")], track_y=3.2)
    lo.route_net("in",  [("Mp", "G"), ("Mn", "G")], track_y=3.7, mkport=mkport)
    lo.route_net("vbp", [("Mcp", "G")], track_y=4.2, mkport=mkport)
    lo.route_net("vbn", [("Mcn", "G")], track_y=4.7, mkport=mkport)
    lo.route_net("VDD", [("Mcp", "S"), ("Mcp", "B"), ("Mp", "B")], track_y=-2.7, mkport=mkport)
    lo.route_net("VSS", [("Mcn", "S"), ("Mcn", "B"), ("Mn", "B")], track_y=-3.2, mkport=mkport)
    lo.finish(outdir)
    return lo


def build_ring_oscillator(outdir, mkport=True):
    """Full current-starved ring oscillator, 2-ROW (PMOS over NMOS) with channel routing.
       Ring nodes are short, isolated wires in the empty channel between the rows -> the
       dense parallel-track field (which dumped ~60 fF of coupling onto every ring node in
       the flat layout) is gone. Ports: VDD VSS ibias clk."""
    lo = Layout("ring_oscillator")
    lo.header()
    lo.begin_cell()

    P = 3.6          # column pitch
    yp, yn = 3.6, -3.6   # PMOS / NMOS row centres; channel is the empty band around y=0

    # ---- placement: column k at x = k*P; PMOS in the top row, NMOS in the bottom row ----
    # bias: col0 (Mbp top, Mbn bot), col1 (Mmir bot). Mp_i (inverter pull-up) is FLIPPED so
    # its gate faces the channel next to Mn_i's gate.
    lo.place("Mbp", "pmos_2_0p5", 0 * P, yp)
    lo.place("Mbn", "nmos_1_0p5", 0 * P, yn)
    lo.place("Mmir", "nmos_1_0p5", 1 * P, yn)
    for i in range(1, 6):
        ca, cb = (2 + 2 * (i - 1)) * P, (3 + 2 * (i - 1)) * P
        lo.place(f"Mcp{i}", "pmos_2_0p5", ca, yp)
        lo.place(f"Mcn{i}", "nmos_1_0p5", ca, yn)
        lo.place(f"Mp{i}", "pmos_1_0p13", cb, yp, flipy=True)
        lo.place(f"Mn{i}", "nmos_0p5_0p13", cb, yn)
    lo.place("Mb1p", "pmos_1_0p13", 12 * P, yp, flipy=True)
    lo.place("Mb1n", "nmos_0p5_0p13", 12 * P, yn)
    lo.place("Mb2p", "pmos_2_0p13", 13 * P, yp, flipy=True)
    lo.place("Mb2n", "nmos_1_0p13", 13 * P, yn)

    nets = {}

    def add(inst, **conn):
        for term, net in conn.items():
            nets.setdefault(net, []).append((inst, term))

    add("Mbn",  D="ibias", G="ibias", S="VSS", B="VSS")
    add("Mmir", D="vbp",   G="ibias", S="VSS", B="VSS")
    add("Mbp",  D="vbp",   G="vbp",   S="VDD", B="VDD")
    nin = {1: "n5", 2: "n1", 3: "n2", 4: "n3", 5: "n4"}
    for i in range(1, 6):
        add(f"Mcp{i}", D=f"pp{i}", G="vbp",   S="VDD",    B="VDD")
        add(f"Mp{i}",  D=f"n{i}",  G=nin[i],  S=f"pp{i}",  B="VDD")
        add(f"Mn{i}",  D=f"n{i}",  G=nin[i],  S=f"nn{i}",  B="VSS")
        add(f"Mcn{i}", D=f"nn{i}", G="ibias", S="VSS",     B="VSS")
    add("Mb1p", D="b1",  G="n5", S="VDD", B="VDD")
    add("Mb1n", D="b1",  G="n5", S="VSS", B="VSS")
    add("Mb2p", D="clk", G="b1", S="VDD", B="VDD")
    add("Mb2n", D="clk", G="b1", S="VSS", B="VSS")

    # GLOBAL DC nets on rails at the row periphery (far from the channel -> they don't
    # load the ring nodes): VDD/vbp high, VSS/ibias low.
    ports = {"VDD", "VSS", "ibias", "clk"}
    # vbp/ibias on M3, VDD/VSS on M4 — so the current-source gate (vbp/ibias) and bulk
    # (VDD/VSS), which sit at the same device centre-x, route on different layers and the
    # coincident vertical jogs don't short.
    # Track lanes (no crossings): vbp/ibias on M3 just above the gates; VDD/VSS on M4 up
    # top (their M4 bulk jogs cross the M3 tracks freely). pp/nn (M4 jogs, M3 track) sit
    # between, not crossed on their own layer.
    lo.route_net("vbp",   nets.pop("vbp"),   track_y=5.0,  top="m3")
    lo.route_net("ibias", nets.pop("ibias"), track_y=-4.0, mkport=mkport, top="m3")
    lo.route_net("VDD",   nets.pop("VDD"),   track_y=8.0,  mkport=mkport, top="m4", w=1.5)
    lo.route_net("VSS",   nets.pop("VSS"),   track_y=-8.0, mkport=mkport, top="m4", w=1.5)
    # RING NODES in the channel (alternating trunk heights so neighbours don't overlap)
    ring_hop = {"n1": 0.0, "n2": 0.7, "n3": 0.0, "n4": 0.7, "n5": -0.7}
    for net, hy in ring_hop.items():
        lo.route_ring(net, nets.pop(net), hop_y=hy)
    lo.route_ring("b1", nets.pop("b1"), hop_y=0.0)
    lo.route_ring("clk", nets.pop("clk"), hop_y=0.7, mkport=mkport)
    # internal starved-supply nodes pp_i (top row) / nn_i (bottom row): short M3 in-row
    for i in range(1, 6):
        lo.route_net(f"pp{i}", nets.pop(f"pp{i}"), track_y=yp + 2.0)
        lo.route_net(f"nn{i}", nets.pop(f"nn{i}"), track_y=yn - 2.0)
    assert not nets, f"unrouted nets: {list(nets)}"

    lo.finish(outdir)
    return lo


BUILDERS = {"cs_stage": build_cs_stage, "ring_oscillator": build_ring_oscillator}

if __name__ == "__main__":
    cell = sys.argv[1] if len(sys.argv) > 1 else "ring_oscillator"
    outdir = sys.argv[2] if len(sys.argv) > 2 else "layout"
    sys.stdout.write(BUILDERS[cell](outdir, mkport="--noport" not in sys.argv).tcl())
