#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Davide Schiavone
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
"""
Scripted analog layout generator for the FLL macros (ihp-sg13g2), emitting a Magic
TCL script that is run headless to produce <cell>.mag / <cell>.gds.

Approach (validated headless, see macros/ring_oscillator/RING_OSCILLATOR_LAYOUT.md §1):
  * Devices: PDK gencells via `magic::gencell_makecell sg13g2::sg13_lv_{n,p}mos ...`
    with `guard 1` so each device is self-contained (own nwell/psub tap ring + B port).
  * Placement: `getcell <dev> child 0 0 parent <x_lambda> <y_lambda>` puts the device
    CENTRE at (x,y). Parent coords are in LAMBDA (1 lambda = 2 internal units = 0.01 um).
  * Routing: each device terminal is brought up through an M1->M2->M3->M4 via stack at
    the terminal; nets then route on M3 (horizontal tracks, unique y per net) and M4
    (vertical jogs, unique x per terminal). M3/M4 are empty above the devices, so the
    over-the-cell router never collides with device metal. metal5 is never used
    (forbidden in the TinyTapeout user area).

Units: layout coordinates here are in MICRONS. 1 um = 100 lambda = 200 internal units.

This module provides a tiny Layout helper + device port tables; per-cell builders live
in the macro generators (e.g. macros/ring_oscillator/scripts/gen_ro_layout.py).
"""

UM_TO_IU = 200.0       # getcell parent refpoint is in internal units (1 um = 200 iu)
IU = 0.005             # 1 internal unit = 0.005 um (for reference)

# Device port offsets (in um, relative to device centre), probed from the gencells with
# guard=1.  fhw/fhh = FULL bbox half-extents in um (incl. nwell/guard halo) — used for
# overlap-free placement (the device's drawn extent is much larger than the diffusion).
#   key -> dict(kind, w, l, fhw, fhh, ports={D,S,G,B:(dx,dy)})
DEVICES = {
    # current-starved RO stage devices
    "pmos_2_0p5":  dict(kind="pmos", w=2.0,  l=0.5,  fhw=1.41,  fhh=2.05,
                        ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 1.22), B=(0.0, -1.59))),
    "pmos_1_0p13": dict(kind="pmos", w=1.0,  l=0.13, fhw=1.225, fhh=1.55,
                        ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
    "nmos_0p5_0p13": dict(kind="nmos", w=0.5, l=0.13, fhw=1.225, fhh=1.30,
                        ports=dict(D=(-0.255, 0.0), S=(0.255, 0.0), G=(0.0, 0.47), B=(0.0, -0.84))),
    "nmos_1_0p5":  dict(kind="nmos", w=1.0,  l=0.5,  fhw=1.41,  fhh=1.55,
                        ports=dict(D=(-0.44, 0.0), S=(0.44, 0.0), G=(0.0, 0.72), B=(0.0, -1.09))),
}

# routing geometry (um)
WIRE_W = 0.20          # default M3/M4 wire width
VIA_S  = 0.30          # via-stack square side


class Layout:
    """Accumulates Magic TCL for one cell."""

    def __init__(self, cell):
        self.cell = cell
        self.devseen = {}        # devkey -> tcl var name holding the device cell name
        self.pre = []            # preamble (gds rescale, snap)
        self.devlines = []       # device makecell calls (must run before placement)
        self.lines = []          # cell body (placement + routing)
        self.insts = {}          # instname -> (devkey, cx, cy)
        self.ports = []          # (net, layer) to label+portify

    # ---- emission helpers ----
    def _emit(self, s):
        self.lines.append(s)

    def header(self):
        self.pre.append("# AUTO-GENERATED by scripts/genlayout.py — do not edit by hand.")
        self.pre.append("gds rescale false")
        self.pre.append("snap internal")

    def make_device(self, devkey):
        if devkey in self.devseen:
            return
        d = DEVICES[devkey]
        var = "dev_" + devkey
        gc = "sg13_lv_pmos" if d["kind"] == "pmos" else "sg13_lv_nmos"
        self.devlines.append(f"set {var} [magic::gencell_makecell sg13g2::{gc} "
                             f"w {d['w']} l {d['l']} ng 1 m 1 guard 1]")
        self.devseen[devkey] = var

    def begin_cell(self):
        pass  # cell creation is inserted in tcl() after all device makecells

    def place(self, inst, devkey, cx, cy):
        """Place device CENTRE at (cx,cy) um."""
        self.make_device(devkey)
        var = self.devseen[devkey]
        lx = round(cx * UM_TO_IU)
        ly = round(cy * UM_TO_IU)
        self._emit(f"getcell ${var} child 0 0 parent {lx} {ly}")
        # getcell renames the just-placed instance to the default; identify it
        self._emit(f"identify {inst}")
        self.insts[inst] = (devkey, cx, cy)

    def place_row(self, specs, gap=0.7, y=0.0):
        """Place devices left-to-right with `gap` (um) between full bboxes.
        specs: list of (inst, devkey). Returns dict inst->cx."""
        cx = 0.0
        prev_fhw = None
        centers = {}
        for inst, devkey in specs:
            fhw = DEVICES[devkey]["fhw"]
            if prev_fhw is not None:
                cx += prev_fhw + gap + fhw
            self.place(inst, devkey, cx, y)
            centers[inst] = cx
            prev_fhw = fhw
        return centers

    def port_xy(self, inst, term):
        devkey, cx, cy = self.insts[inst]
        dx, dy = DEVICES[devkey]["ports"][term]
        return (cx + dx, cy + dy)

    # ---- painting ----
    def rect(self, layer, x0, y0, x1, y1):
        x0, x1 = sorted((x0, x1))
        y0, y1 = sorted((y0, y1))
        self._emit(f"box {x0:.3f}um {y0:.3f}um {x1:.3f}um {y1:.3f}um")
        self._emit(f"paint {layer}")

    def via_stack(self, x, y, top="m4", s=VIA_S):
        """Via stack at (x,y) connecting device M1 up to `top` (m3 or m4)."""
        h = s / 2.0
        self.rect("m1", x - h, y - h, x + h, y + h)
        self.rect("via1", x - h, y - h, x + h, y + h)
        self.rect("via2", x - h, y - h, x + h, y + h)
        if top == "m4":
            self.rect("via3", x - h, y - h, x + h, y + h)

    def vwire(self, layer, x, y0, y1, w=WIRE_W):
        self.rect(layer, x - w / 2, y0, x + w / 2, y1)

    def hwire(self, layer, y, x0, x1, w=WIRE_W):
        self.rect(layer, x0, y - w / 2, x1, y + w / 2)

    def via3_at(self, x, y, s=VIA_S):
        h = s / 2.0
        self.rect("via3", x - h, y - h, x + h, y + h)

    def label(self, net, layer, x, y, mkport=True):
        if mkport:
            self.ports.append((net, layer, x, y))

    # ---- net routing ----
    def route_net(self, net, terms, track_y, mkport=False, port_layer="m3"):
        """terms: list of (inst, term). Bring each terminal up via stack -> M4 vertical
        jog -> via3 -> M3 horizontal track at track_y connecting them all."""
        pts = [self.port_xy(i, t) for (i, t) in terms]
        xs = [p[0] for p in pts]
        # M3 horizontal track
        if len(pts) > 1:
            self.hwire("m3", track_y, min(xs) - 0.1, max(xs) + 0.1)
        for (px, py) in pts:
            self.via_stack(px, py, top="m4")          # device -> M4
            self.vwire("m4", px, py, track_y)          # vertical jog on M4
            self.via3_at(px, track_y)                  # M4 -> M3 at the track
        # ensure an M3 patch even for single-terminal nets (for labelling/port)
        if len(pts) == 1:
            px, py = pts[0]
            self.hwire("m3", track_y, px - 0.15, px + 0.15)
        if mkport:
            self.label(net, port_layer, xs[0], track_y, mkport=True)

    def finish(self, outdir):
        # make the labelled nets into ports: place label on its M3 track, select it,
        # and declare it a subcircuit port.
        for i, (net, layer, x, y) in enumerate(self.ports):
            self._emit(f"box {x:.3f}um {y:.3f}um {x:.3f}um {y:.3f}um")
            self._emit(f"label {net} center {layer}")
            # port make operates on the single label under the (still-point) cursor box
            self._emit(f"port make {i + 1}")
        # NB: save with the bare cell name (run Magic with cwd=layout dir) so the cell
        # is named "<cell>", not "<path>/<cell>".
        self._emit("select top cell")
        self._emit(f"save {self.cell}")
        # write all device subcells to disk too, so .mag-based LVS extraction (which
        # preserves ports, unlike a GDS round-trip) can resolve the hierarchy.
        self._emit("writeall force")
        self._emit(f"gds write {self.cell}.gds")
        self._emit(f'puts "GEN_DONE {self.cell}"')
        self._emit("quit -noprompt")

    def tcl(self):
        create = [f"cellname create {self.cell}", f"load {self.cell}"]
        return "\n".join(self.pre + self.devlines + create + self.lines) + "\n"
